### ISSUE TITLE
Missing command make foss-ag great-again

### ISSUE THREAD

**Issue by davidmehren** [foss-ag/design_id#1]
This command needs to generate a version of our logo with
![](https://ih1.redbubble.net/image.273808371.6220/ap,550x550,12x16,1,transparent,t.u1.png)

**Comment by Lazalatin** [comment]
I believe that we have exhaustively discussed how much effort we will put into political statements as an organisation. Therefore, even if Mr. Trumps "winning face" could be labeled as an internet meme, I vote for closing and ignoring this matter.

**Comment by davidmehren** [comment]
😢

**Comment by Scosh** [comment]
😭🕺💃 
https://youtu.be/ZSM3w1v-A_Y
