### ISSUE TITLE
Tiny gap between top star's lower right arm?

### ISSUE THREAD

**Issue by Scosh** [foss-ag/design_id#10]
Okay … I might be going crazy from looking at things for too long, but while doing some work with different colours, I noticed that the gap where the diagonal arms of the stars should meet appear to be a different side on the right than on the left?

They are essentially minuscule … and *should* only be observable when zooming in ridiculously close, but when just looking at these from afar, I still felt like I noticed there was a different gap on the right side.

I did some pixel-pinching in both Inkscape using the original vectors and made a .png export to check if it was just an artefact of the software and not something that is exported.

Screenshots follow of me comparing them:

## Vectors

![2017-12-02-222337_1900x1129_scrot](https://user-images.githubusercontent.com/5603235/33519884-74a9d4b4-d7b0-11e7-8317-a421b4e6e44f.png)

![2017-12-02-222324_1900x1129_scrot](https://user-images.githubusercontent.com/5603235/33519880-6a4fd702-d7b0-11e7-82c6-e02c25d719e8.png)

![2017-12-02-222251_1900x1129_scrot](https://user-images.githubusercontent.com/5603235/33519876-59193fa0-d7b0-11e7-8276-cf6de393d399.png)

![2017-12-02-222234_1900x1129_scrot](https://user-images.githubusercontent.com/5603235/33519873-45e48246-d7b0-11e7-8640-8bcea757ffa9.png)

## Bitmap

![2017-12-02-222410_1900x1129_scrot](https://user-images.githubusercontent.com/5603235/33519895-96080072-d7b0-11e7-985a-686e76b330e0.png)

![2017-12-02-222356_1900x1129_scrot](https://user-images.githubusercontent.com/5603235/33519899-9a20f556-d7b0-11e7-9d8b-a4e34e663d41.png)

The background colour seems to bleed through a tiny bit, which doesn't happen where the two lower stars meet at a 90 degree angle.

In my tests this wasn't so severe or observable with our normal FOSS-AG logo colours, but was more noticeable using different colours.

If you want to compare these for yourselves, the files, including a high-resolution .png, can be found in the current version of our `design_playground` repository on our Gitea.

---

Could this just be a concession of having diagonal lines trying to meet? Or is Inkscape not aligning things perfectly and the pixel values where they should be meeting are actually different/wrong?

Please tell me if I am actually going insane and there is nothing to worry about or see here.

**Comment by Scosh** [comment]
Na … I'm not going crazy, that gap definitely **is there in the export**, but it's on *both* sides, not just on the right:

## Bitmap

![2017-12-02-225120_1900x1129_scrot](https://user-images.githubusercontent.com/5603235/33520015-023ca8fe-d7b3-11e7-9fa3-0db1fe86a27a.png)

**Comment by Scosh** [comment]
This isn't even completely remedied when you combine the shapes using **Union**, btw:

## Bitmap

![2017-12-02-225448_1900x1129_scrot](https://user-images.githubusercontent.com/5603235/33520044-6de3130e-d7b3-11e7-8b68-1576a774b0c2.png)

So we definitely need to try to fix this.

**Comment by Scosh** [comment]
The example files used in the first post can now be found at:

`FOSS-AG/design_playground/src/master/social-media/website`

on our Gitea.

**Comment by fes0j** [comment]
I think this could be solved by applying a small border; not just rely on the "fill" part of the svg.
This might be a dirty solution.

**Comment by fes0j** [comment]
Under further investigation it turns out: the vector for each point of the star varies where they should be the same. 
I'll link this to issue #2, this is part of the clean up.
Though this is not enough to resolve this issue :(
Read [Inkscape FAQ](https://inkscape.org/en/learn/faq/#theres-seam-or-artifact-between-adjacent-objects-sharing-same-border-or-between-patterns) "There's a seam, or artifact, between adjacent objects sharing the same border, or between patterns"

**Comment by Scosh** [comment]
Please try this and commit! Let's see what it looks like.

**Comment by Scosh** [comment]
Closing this for now. Seems a lot better from the machine I'm currently looking at this from. Might re-open if we want to try a different method at a later point or change something about the base design.
