### ISSUE TITLE
Add fonts as Git submodule

### ISSUE THREAD

**Issue by Scosh** [foss-ag/design_id#11]
The fonts we use for our branding (which must still be decided on finally) should be included in this repository.

One way this could be accomplished which was briefly discussed at a meeting, was to add an external repository containing the needed fonts as a Git `submodule`.

The best technical execution would allow the fonts to stay as up-to-date as possible with their respective master branches/versions … but how do we do this while maintaining control of *what* goes into our repository and *what* does not?

**Comment by dragetd** [comment]
Personally, I think submodules are inherently PITA to manage. I'd recommend bundling releases (or just taking master) of the other repository and copying it over.

If submodules are used, specify the https:// url and not git@, to allow anonymous cloning. :)

**Comment by davidmehren** [comment]
I would not add copy contents of other repos. That makes keeping things up-to-date very tedious.
If we don't want Submodules, I would propose: 
- Let the buildscript download and extract a release tarball with a pinned version (aka build our own makeshift dependency manager)
- Use a real dependency manager like composer, npm, bundler or whatever.

**Comment by dragetd** [comment]
I was a little frustrated when I wrote that. Maybe gitsubmodules are the right thing. :)

**Comment by dragetd** [comment]
Then again, should a logo track the updates of a font? Shouldn't it be rather identical, even if the upstream font maintainer decides to change the font? Just adding the font file might be not the coolest and most technical solution, but the most practical one. :D

But managing the fonts with a git submodule is also ok. Just keep to the git commands and do not manually fiddle with the .gitmodules file.
It could look like this:
```
git add submodule https://github.com/Scosh/fonts.git scosh_fonts
cd scosh_fonts
git checkout <tag_or_commit_we_want_to_keep_using>
cd ..
git status
git commit -a
#submodule now pinned to certain commit
```

But when trying this locally, I noticed that you repository is 600MB! That is a lot. xD

**Comment by Scosh** [comment]
> Then again, should a logo track the updates of a font? Shouldn't it be rather identical, even if the upstream font maintainer decides to change the font?

I don't exactly know what you mean with either of these statements … :D 

---

> Just adding the font file might be not the coolest and most technical solution, but the most practical one. :D

I agree. Fonts make the whole idea of this repository significantly more complicated … 

There is a certain disconnect between either storing a large amount of fonts that can be accessed quickly or keeping the repository small, source-based and 'reproducible.' I'm still very unsure and undecided on how to best address these problems.

---

> But when trying this locally, I noticed that you repository is 600MB! That is a lot. xD

Oh yes 🙈 please **don't** use the current version of that repository as _any_ kind of base for anything  … ^^' It's a serious mess right now, and kind of shows a lot of my early git/GitHub naiveté. 

There are unfortunately a lot of duplicate font files (because some fonts deliver both ttf and otf versions), some huge source files, unnecessary images … etc. etc. It needs a lot of restructuring.

The way most fonts are delivered on GitHub is part of the difficulty of adding them cleanly to anything new. For a collection like mine, I would actually have to edit and streamline their contents. But modifying things makes updating more difficult again …

**Comment by Scosh** [comment]
> I would not add copy contents of other repos. That makes keeping things up-to-date very tedious.
> If we don't want Submodules, I would propose: 
> - Let the buildscript download and extract a release tarball with a pinned version (aka build our own makeshift dependency manager)
> - Use a real dependency manager like composer, npm, bundler or whatever.

Perhaps @davidmehren's suggestion is thinking in the best direction for our needs? :) Though I don't know any of the mentioned dependency managers (except npm), and have little experience working with them …

And for npm: if it wasn't predictable enough already … I'm still generally saying no to anything JavaScript, sorry. ^^ Plus, I've had numerous terrible experiences already while trying to use npm for myself in the past.

**Comment by Scosh** [comment]
cf. the [font-install](https://github.com/Crosse/font-install) GitHub project.

May be what we need to solve this problem!?

Security issues (having to rely on external sites like [fontsquirrel](https://www.fontsquirrel.com/) to get files) were already discussed in an irl meeting with @fes0j @InnayTool @Scosh … Don't know yet what we can do about this, though.

**Comment by dragetd** [comment]
> I don't exactly know what you mean with either of these statements … :D

I mean, when you create a logo or a design for something, unlike with software, you do not want to update your dependencies. Updating dependencies is done to avoid security issues and eventually add features.

Both things do not apply to logos or designs.
You want your logo/design to be pixel-identical even for future releases. Imagine we use your font repository and some day you replace the font we use with something silly.

Don't get me wrong, I am a big fan of automation, clean dependencies and such but in this case it really feels like we are overengineering this. Especially if we consider hacking our own Make file or buildscript.

We could look into font-install. But maybe it is sufficient to just add a README.md file with the two needed commands to install the font and be done with it. :P

**Comment by fes0j** [comment]
We already have "manual dependency": the Swatch Palette.
A change there for example could heavily influence new creations or existing artwork.

The moment we decide to use a font in a logo, it becomes a fixed design element. I think, the font has to be useable right from the beginning and shouldn't need changing afterwards anyway.

I agree with dragetd. If we do update dependencies, it should be a manual process where we discuss why we need to update.

**Comment by fes0j** [comment]
My suggestion for the time being: Just put the necessary fonts in a `res`-folder, so we can move forward.
As we expand and grow, we can improve the font install process.

**Comment by Scosh** [comment]
Suggestion:

- This repository (`design_id`) will contain **hand-picked versions** of the fonts.
    - These files will only be updated if significant design changes happen to our logo and/or other materials.
    - There will likely be **3** fonts in this repo:
        - one **header** font
        - one **body copy** font
        - one **monospaced/code** font
- A larger (FOSS-AG?) project will contain a **general collection** of many more, quality open source fonts. It will be a port of [Scosh/fonts](https://github.com/Scosh/fonts).*

(I explicitly said **port, not fork,** here, because it **will not be a fork.** :D Not of the current version of `Scosh/fonts`, anyway. It would be a cleaner **revamp of the same idea.**)

**Comment by fes0j** [comment]
With the merge of dev into master f32e6d0cdd10e033b9419f50c8d43c900525bee6 design_font is now a submodule.
