### ISSUE TITLE
Different variations of the FOSS-AG sticker

### ISSUE THREAD

**Issue by lxndio** [foss-ag/design_id#19]
As discussed today, February 15 2018, it may be sensible to have different variations of the FOSS-AG sticker printed in the next batch.

These variations could include different colours (fore- and background) or other shapes (e.g. not making round sticker but rather cutting out the asterisk symbols on the sticker precisely (or with small border).

As always, open for all kinds of feedback …

**Comment by Scosh** [comment]
These could be discussed here and would then (in their final release form) go into a separate place for editing and later releases.

**Comment by fes0j** [comment]
Closing this issue because of age and the other available issues in the foss-ag/design repo.
Since than we've printed new stickers in different sizes. If different color are still desired, please open a new issue over there ;-)
