### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by Scosh** [foss-ag/design_id#7]
An appropriate license for this repository needs to be decided on and included as a text file, as per convention.

The license potentially needs to encompass **art assets** as well as **software code**.

Suggestions are welcome.

**Comment by Lazalatin** [comment]
After talking with @Scosh and @Eisfunke we are suggesting the following licence:

-----

<a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="Creative Commons Lizenzvertrag" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/4.0/88x31.png" /></a><br />Dieses Werk ist lizenziert unter einer <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">Creative Commons Namensnennung - Nicht kommerziell - Keine Bearbeitungen 4.0 International Lizenz</a>

-----
Optionally with metadata?
This is a very restrictive licence which can be made less restrictive later if needed.
