### ISSUE TITLE
Add reliable method to have FOSS-AG colours as swatches at the botttom of inkscape documents

### ISSUE THREAD

**Issue by Scosh** [foss-ag/design_id#9]
As you've shown me already, @fes0j, there is a way to have a custom colour-bar at the bottom of Inkscape documents. This method still needs to be integrated into this repository and documented, so everyone can use it when creating FOSS-AG assets.

**Comment by fes0j** [comment]
There is now a FOSS-AG palette available. Use this either by importing it into gimp or manually moving it to the corresponding Inkscap resource folder. Introduced by 54d0ef15f977d579b346d72a13fbe13748ecd220
